/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as A6b8RouteImport } from './routes/a6b8'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as IssuesSlugRouteImport } from './routes/issues.$slug'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSubmissionsIndexRouteImport } from './routes/_authenticated/admin.submissions.index'
import { Route as AuthenticatedAdminSponsorsIndexRouteImport } from './routes/_authenticated/admin.sponsors.index'
import { Route as AuthenticatedAdminJobsIndexRouteImport } from './routes/_authenticated/admin.jobs.index'
import { Route as AuthenticatedAdminIssuesIndexRouteImport } from './routes/_authenticated/admin.issues.index'
import { Route as AuthenticatedAdminEventsIndexRouteImport } from './routes/_authenticated/admin.events.index'
import { Route as AuthenticatedAdminDealsIndexRouteImport } from './routes/_authenticated/admin.deals.index'
import { Route as ApiPublicBrandSplatRouteImport } from './routes/api/public/brand.$'
import { Route as AuthenticatedAdminSubmissionsIdRouteImport } from './routes/_authenticated/admin.submissions.$id'
import { Route as AuthenticatedAdminJobsNewRouteImport } from './routes/_authenticated/admin.jobs.new'
import { Route as AuthenticatedAdminJobsIdRouteImport } from './routes/_authenticated/admin.jobs.$id'
import { Route as AuthenticatedAdminIssuesNewRouteImport } from './routes/_authenticated/admin.issues.new'
import { Route as AuthenticatedAdminIssuesIdRouteImport } from './routes/_authenticated/admin.issues.$id'
import { Route as AuthenticatedAdminEventsNewRouteImport } from './routes/_authenticated/admin.events.new'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated/admin.events.$id'
import { Route as AuthenticatedAdminDealsNewRouteImport } from './routes/_authenticated/admin.deals.new'
import { Route as AuthenticatedAdminDealsIdRouteImport } from './routes/_authenticated/admin.deals.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const A6b8Route = A6b8RouteImport.update({
  id: '/a6b8',
  path: '/a6b8',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSlugRoute = IssuesSlugRouteImport.update({
  id: '/issues/$slug',
  path: '/issues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubmissionsIndexRoute =
  AuthenticatedAdminSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSponsorsIndexRoute =
  AuthenticatedAdminSponsorsIndexRouteImport.update({
    id: '/sponsors/',
    path: '/sponsors/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsIndexRoute =
  AuthenticatedAdminJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIssuesIndexRoute =
  AuthenticatedAdminIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsIndexRoute =
  AuthenticatedAdminEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealsIndexRoute =
  AuthenticatedAdminDealsIndexRouteImport.update({
    id: '/deals/',
    path: '/deals/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicBrandSplatRoute = ApiPublicBrandSplatRouteImport.update({
  id: '/api/public/brand/$',
  path: '/api/public/brand/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubmissionsIdRoute =
  AuthenticatedAdminSubmissionsIdRouteImport.update({
    id: '/submissions/$id',
    path: '/submissions/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsNewRoute =
  AuthenticatedAdminJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsIdRoute =
  AuthenticatedAdminJobsIdRouteImport.update({
    id: '/jobs/$id',
    path: '/jobs/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIssuesNewRoute =
  AuthenticatedAdminIssuesNewRouteImport.update({
    id: '/issues/new',
    path: '/issues/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIssuesIdRoute =
  AuthenticatedAdminIssuesIdRouteImport.update({
    id: '/issues/$id',
    path: '/issues/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsNewRoute =
  AuthenticatedAdminEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealsNewRoute =
  AuthenticatedAdminDealsNewRouteImport.update({
    id: '/deals/new',
    path: '/deals/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealsIdRoute =
  AuthenticatedAdminDealsIdRouteImport.update({
    id: '/deals/$id',
    path: '/deals/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a6b8': typeof A6b8Route
  '/archive': typeof ArchiveRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/deals/$dealId': typeof DealsDealIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/issues/$slug': typeof IssuesSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/deals/': typeof DealsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/deals/$id': typeof AuthenticatedAdminDealsIdRoute
  '/admin/deals/new': typeof AuthenticatedAdminDealsNewRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/admin/issues/$id': typeof AuthenticatedAdminIssuesIdRoute
  '/admin/issues/new': typeof AuthenticatedAdminIssuesNewRoute
  '/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/admin/submissions/$id': typeof AuthenticatedAdminSubmissionsIdRoute
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/admin/deals/': typeof AuthenticatedAdminDealsIndexRoute
  '/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
  '/admin/issues/': typeof AuthenticatedAdminIssuesIndexRoute
  '/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/sponsors/': typeof AuthenticatedAdminSponsorsIndexRoute
  '/admin/submissions/': typeof AuthenticatedAdminSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a6b8': typeof A6b8Route
  '/archive': typeof ArchiveRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/issues/$slug': typeof IssuesSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/deals': typeof DealsIndexRoute
  '/events': typeof EventsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/deals/$id': typeof AuthenticatedAdminDealsIdRoute
  '/admin/deals/new': typeof AuthenticatedAdminDealsNewRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/admin/issues/$id': typeof AuthenticatedAdminIssuesIdRoute
  '/admin/issues/new': typeof AuthenticatedAdminIssuesNewRoute
  '/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/admin/submissions/$id': typeof AuthenticatedAdminSubmissionsIdRoute
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/admin/deals': typeof AuthenticatedAdminDealsIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsIndexRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesIndexRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsIndexRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a6b8': typeof A6b8Route
  '/archive': typeof ArchiveRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/deals/$dealId': typeof DealsDealIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/issues/$slug': typeof IssuesSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/deals/': typeof DealsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/deals/$id': typeof AuthenticatedAdminDealsIdRoute
  '/_authenticated/admin/deals/new': typeof AuthenticatedAdminDealsNewRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/_authenticated/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/_authenticated/admin/issues/$id': typeof AuthenticatedAdminIssuesIdRoute
  '/_authenticated/admin/issues/new': typeof AuthenticatedAdminIssuesNewRoute
  '/_authenticated/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/_authenticated/admin/jobs/new': typeof AuthenticatedAdminJobsNewRoute
  '/_authenticated/admin/submissions/$id': typeof AuthenticatedAdminSubmissionsIdRoute
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/_authenticated/admin/deals/': typeof AuthenticatedAdminDealsIndexRoute
  '/_authenticated/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
  '/_authenticated/admin/issues/': typeof AuthenticatedAdminIssuesIndexRoute
  '/_authenticated/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/_authenticated/admin/sponsors/': typeof AuthenticatedAdminSponsorsIndexRoute
  '/_authenticated/admin/submissions/': typeof AuthenticatedAdminSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a6b8'
    | '/archive'
    | '/privacy'
    | '/sitemap.xml'
    | '/sponsor'
    | '/submit'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/deals/$dealId'
    | '/events/$eventId'
    | '/issues/$slug'
    | '/jobs/$jobId'
    | '/deals/'
    | '/events/'
    | '/jobs/'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin/'
    | '/admin/deals/$id'
    | '/admin/deals/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/issues/$id'
    | '/admin/issues/new'
    | '/admin/jobs/$id'
    | '/admin/jobs/new'
    | '/admin/submissions/$id'
    | '/api/public/brand/$'
    | '/admin/deals/'
    | '/admin/events/'
    | '/admin/issues/'
    | '/admin/jobs/'
    | '/admin/sponsors/'
    | '/admin/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a6b8'
    | '/archive'
    | '/privacy'
    | '/sitemap.xml'
    | '/sponsor'
    | '/submit'
    | '/terms'
    | '/unsubscribe'
    | '/deals/$dealId'
    | '/events/$eventId'
    | '/issues/$slug'
    | '/jobs/$jobId'
    | '/deals'
    | '/events'
    | '/jobs'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin'
    | '/admin/deals/$id'
    | '/admin/deals/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/issues/$id'
    | '/admin/issues/new'
    | '/admin/jobs/$id'
    | '/admin/jobs/new'
    | '/admin/submissions/$id'
    | '/api/public/brand/$'
    | '/admin/deals'
    | '/admin/events'
    | '/admin/issues'
    | '/admin/jobs'
    | '/admin/sponsors'
    | '/admin/submissions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a6b8'
    | '/archive'
    | '/privacy'
    | '/sitemap.xml'
    | '/sponsor'
    | '/submit'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/deals/$dealId'
    | '/events/$eventId'
    | '/issues/$slug'
    | '/jobs/$jobId'
    | '/deals/'
    | '/events/'
    | '/jobs/'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/deals/$id'
    | '/_authenticated/admin/deals/new'
    | '/_authenticated/admin/events/$id'
    | '/_authenticated/admin/events/new'
    | '/_authenticated/admin/issues/$id'
    | '/_authenticated/admin/issues/new'
    | '/_authenticated/admin/jobs/$id'
    | '/_authenticated/admin/jobs/new'
    | '/_authenticated/admin/submissions/$id'
    | '/api/public/brand/$'
    | '/_authenticated/admin/deals/'
    | '/_authenticated/admin/events/'
    | '/_authenticated/admin/issues/'
    | '/_authenticated/admin/jobs/'
    | '/_authenticated/admin/sponsors/'
    | '/_authenticated/admin/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  A6b8Route: typeof A6b8Route
  ArchiveRoute: typeof ArchiveRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorRoute: typeof SponsorRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  DealsDealIdRoute: typeof DealsDealIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  IssuesSlugRoute: typeof IssuesSlugRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  DealsIndexRoute: typeof DealsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiPublicBrandSplatRoute: typeof ApiPublicBrandSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a6b8': {
      id: '/a6b8'
      path: '/a6b8'
      fullPath: '/a6b8'
      preLoaderRoute: typeof A6b8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$slug': {
      id: '/issues/$slug'
      path: '/issues/$slug'
      fullPath: '/issues/$slug'
      preLoaderRoute: typeof IssuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions/': {
      id: '/_authenticated/admin/submissions/'
      path: '/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sponsors/': {
      id: '/_authenticated/admin/sponsors/'
      path: '/sponsors'
      fullPath: '/admin/sponsors/'
      preLoaderRoute: typeof AuthenticatedAdminSponsorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/': {
      id: '/_authenticated/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedAdminJobsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/issues/': {
      id: '/_authenticated/admin/issues/'
      path: '/issues'
      fullPath: '/admin/issues/'
      preLoaderRoute: typeof AuthenticatedAdminIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/': {
      id: '/_authenticated/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AuthenticatedAdminEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/deals/': {
      id: '/_authenticated/admin/deals/'
      path: '/deals'
      fullPath: '/admin/deals/'
      preLoaderRoute: typeof AuthenticatedAdminDealsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/brand/$': {
      id: '/api/public/brand/$'
      path: '/api/public/brand/$'
      fullPath: '/api/public/brand/$'
      preLoaderRoute: typeof ApiPublicBrandSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/submissions/$id': {
      id: '/_authenticated/admin/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/admin/submissions/$id'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/new': {
      id: '/_authenticated/admin/jobs/new'
      path: '/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AuthenticatedAdminJobsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/$id': {
      id: '/_authenticated/admin/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AuthenticatedAdminJobsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/issues/new': {
      id: '/_authenticated/admin/issues/new'
      path: '/issues/new'
      fullPath: '/admin/issues/new'
      preLoaderRoute: typeof AuthenticatedAdminIssuesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/issues/$id': {
      id: '/_authenticated/admin/issues/$id'
      path: '/issues/$id'
      fullPath: '/admin/issues/$id'
      preLoaderRoute: typeof AuthenticatedAdminIssuesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/new': {
      id: '/_authenticated/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AuthenticatedAdminEventsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/deals/new': {
      id: '/_authenticated/admin/deals/new'
      path: '/deals/new'
      fullPath: '/admin/deals/new'
      preLoaderRoute: typeof AuthenticatedAdminDealsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/deals/$id': {
      id: '/_authenticated/admin/deals/$id'
      path: '/deals/$id'
      fullPath: '/admin/deals/$id'
      preLoaderRoute: typeof AuthenticatedAdminDealsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDealsIdRoute: typeof AuthenticatedAdminDealsIdRoute
  AuthenticatedAdminDealsNewRoute: typeof AuthenticatedAdminDealsNewRoute
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
  AuthenticatedAdminEventsNewRoute: typeof AuthenticatedAdminEventsNewRoute
  AuthenticatedAdminIssuesIdRoute: typeof AuthenticatedAdminIssuesIdRoute
  AuthenticatedAdminIssuesNewRoute: typeof AuthenticatedAdminIssuesNewRoute
  AuthenticatedAdminJobsIdRoute: typeof AuthenticatedAdminJobsIdRoute
  AuthenticatedAdminJobsNewRoute: typeof AuthenticatedAdminJobsNewRoute
  AuthenticatedAdminSubmissionsIdRoute: typeof AuthenticatedAdminSubmissionsIdRoute
  AuthenticatedAdminDealsIndexRoute: typeof AuthenticatedAdminDealsIndexRoute
  AuthenticatedAdminEventsIndexRoute: typeof AuthenticatedAdminEventsIndexRoute
  AuthenticatedAdminIssuesIndexRoute: typeof AuthenticatedAdminIssuesIndexRoute
  AuthenticatedAdminJobsIndexRoute: typeof AuthenticatedAdminJobsIndexRoute
  AuthenticatedAdminSponsorsIndexRoute: typeof AuthenticatedAdminSponsorsIndexRoute
  AuthenticatedAdminSubmissionsIndexRoute: typeof AuthenticatedAdminSubmissionsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminDealsIdRoute: AuthenticatedAdminDealsIdRoute,
  AuthenticatedAdminDealsNewRoute: AuthenticatedAdminDealsNewRoute,
  AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
  AuthenticatedAdminEventsNewRoute: AuthenticatedAdminEventsNewRoute,
  AuthenticatedAdminIssuesIdRoute: AuthenticatedAdminIssuesIdRoute,
  AuthenticatedAdminIssuesNewRoute: AuthenticatedAdminIssuesNewRoute,
  AuthenticatedAdminJobsIdRoute: AuthenticatedAdminJobsIdRoute,
  AuthenticatedAdminJobsNewRoute: AuthenticatedAdminJobsNewRoute,
  AuthenticatedAdminSubmissionsIdRoute: AuthenticatedAdminSubmissionsIdRoute,
  AuthenticatedAdminDealsIndexRoute: AuthenticatedAdminDealsIndexRoute,
  AuthenticatedAdminEventsIndexRoute: AuthenticatedAdminEventsIndexRoute,
  AuthenticatedAdminIssuesIndexRoute: AuthenticatedAdminIssuesIndexRoute,
  AuthenticatedAdminJobsIndexRoute: AuthenticatedAdminJobsIndexRoute,
  AuthenticatedAdminSponsorsIndexRoute: AuthenticatedAdminSponsorsIndexRoute,
  AuthenticatedAdminSubmissionsIndexRoute:
    AuthenticatedAdminSubmissionsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  A6b8Route: A6b8Route,
  ArchiveRoute: ArchiveRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorRoute: SponsorRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  DealsDealIdRoute: DealsDealIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  IssuesSlugRoute: IssuesSlugRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  DealsIndexRoute: DealsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiPublicBrandSplatRoute: ApiPublicBrandSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
