/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuesSlugRouteImport } from './routes/issues.$slug'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesSlugRoute = IssuesSlugRouteImport.update({
  id: '/issues/$slug',
  path: '/issues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/sponsor': typeof SponsorRoute
  '/submit': typeof SubmitRoute
  '/issues/$slug': typeof IssuesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/sponsor': typeof SponsorRoute
  '/submit': typeof SubmitRoute
  '/issues/$slug': typeof IssuesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/sponsor': typeof SponsorRoute
  '/submit': typeof SubmitRoute
  '/issues/$slug': typeof IssuesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/events'
    | '/privacy'
    | '/sponsor'
    | '/submit'
    | '/issues/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/events'
    | '/privacy'
    | '/sponsor'
    | '/submit'
    | '/issues/$slug'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/events'
    | '/privacy'
    | '/sponsor'
    | '/submit'
    | '/issues/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  EventsRoute: typeof EventsRoute
  PrivacyRoute: typeof PrivacyRoute
  SponsorRoute: typeof SponsorRoute
  SubmitRoute: typeof SubmitRoute
  IssuesSlugRoute: typeof IssuesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$slug': {
      id: '/issues/$slug'
      path: '/issues/$slug'
      fullPath: '/issues/$slug'
      preLoaderRoute: typeof IssuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  EventsRoute: EventsRoute,
  PrivacyRoute: PrivacyRoute,
  SponsorRoute: SponsorRoute,
  SubmitRoute: SubmitRoute,
  IssuesSlugRoute: IssuesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
